### ISSUE TITLE
Not able to pass the tags

### ISSUE THREAD

**Issue by poojakaluskar** [BlueBambooStudios/gatsby-plugin-freshchat#1]
How can I pass tags in this integration to customize the response?

**Comment by haswalt** [comment]
Hi I'm not sure what you mean. Can you clarify or point me to docs on freshchat about tags?

**Comment by poojakaluskar** [comment]
Sure thing.
Please follow this [link](https://developers.freshchat.com/#customisation-chn)

**Comment by haswalt** [comment]
Ah ok, we didn't need this level of configuration so haven't added it to this plugin. I don't mind looking at adding this though, unless you feel like giving it a go?
